stages:
  - web_presence

pages:
  image: node:16.13
  stage: web_presence
  # This folder is cached between builds
  # https://docs.gitlab.com/ce/ci/yaml/README.html#cache
  cache:
    paths:
      - node_modules/
      # Enables git-lab CI caching. Both .cache and public must be cached, otherwise builds will fail.
      - .cache/
      - public/
  script:
    - npm install
    - ./node_modules/.bin/gatsby build --prefix-paths
    - cp src/.htaccess-content public/.htaccess
  artifacts:
    paths:
      - public
  only:
    - main
